### ISSUE TITLE
have any usable sql script

### ISSUE THREAD

**Issue by y497068561** [rdrrichards/QIQO.Database#1]
I can't deploy the database. because my database is sql server 2008,so have any usable sql script for me,thx

**Comment by rdrrichards** [comment]
This database used sequences, which were added to SQL Server in version 2012. Feel free to change the table creation scripts to use IDENTITY, if you like. But, I will not do that for you. I suggest you upgrade your SQL Server to a newer version. MS doesn't really support it anymore.
